services:
  franky-storefront:
    container_name: franky_storefront
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_PATH: /biss-app
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3500:3000"
    environment:
      NEXT_PUBLIC_BASE_PATH: /biss-app
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:3000/biss-app"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
